"""new fields in user model

Revision ID: 070d089cf759
Revises: 40e3b982944f
Create Date: 2019-02-05 10:57:09.838000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '070d089cf759'
down_revision = '40e3b982944f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
